"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class AccountType(str, Enum):
    r"""`investment:` Investment account. In API versions 2018-05-22 and earlier, this type is called `brokerage` instead.

    `credit:` Credit card

    `depository:` Depository account

    `loan:` Loan account

    `other:` Non-specified account type

    See the [Account type schema](https://plaid.com/docs/api/accounts#account-type-schema) for a full listing of account types and corresponding subtypes.
    """
    INVESTMENT = 'investment'
    CREDIT = 'credit'
    DEPOSITORY = 'depository'
    LOAN = 'loan'
    BROKERAGE = 'brokerage'
    OTHER = 'other'
