"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from plaid import utils
from typing import Any, Dict, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class BankTransferBalance:
    r"""Information about the balance of a bank transfer"""
    available: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('available') }})
    r"""The total available balance - the sum of all successful debit transfer amounts minus all credit transfer amounts."""
    transactable: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('transactable') }})
    r"""The transactable balance shows the amount in your account that you are able to use for transfers, and is essentially your available balance minus your minimum balance."""
    additional_properties: Optional[Dict[str, Any]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'exclude': lambda f: f is None }})
    

