"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses


@dataclasses.dataclass
class CategoriesGetRequest:
    r"""CategoriesGetRequest defines the request schema for `/categories/get`"""
    

