"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .counterpartytype import CounterpartyType
from dataclasses_json import Undefined, dataclass_json
from plaid import utils
from typing import Any, Dict, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class Counterparty:
    r"""The counterparty, such as the merchant or financial institution, is extracted by Plaid from the raw description."""
    UNSET='__SPEAKEASY_UNSET__'
    logo_url: Optional[str] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('logo_url') }})
    r"""The URL of a logo associated with the counterparty, if available. The logo is formatted as a 100x100 pixel PNG file."""
    name: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('name') }})
    r"""The name of the counterparty, such as the merchant or the financial institution, as extracted by Plaid from the raw description."""
    type: CounterpartyType = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('type') }})
    r"""The counterparty type.

    `merchant`: a provider of goods or services for purchase
    `financial_institution`: a financial entity (bank, credit union, BNPL, fintech)
    `payment_app`: a transfer or P2P app (e.g. Zelle)
    `marketplace`: a marketplace (e.g DoorDash, Google Play Store)
    `payment_terminal`: a point-of-sale payment terminal (e.g Square, Toast)
    `income_source`: the payer in an income transaction (e.g., an employer, client, or government agency)
    """
    website: Optional[str] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('website') }})
    r"""The website associated with the counterparty."""
    additional_properties: Optional[Dict[str, Any]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'exclude': lambda f: f is None }})
    confidence_level: Optional[str] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('confidence_level'), 'exclude': lambda f: f is Counterparty.UNSET }})
    r"""A description of how confident we are that the provided counterparty is involved in the transaction.

    `VERY_HIGH`: We recognize this counterparty and we are more than 98% confident that it is involved in this transaction.
    `HIGH`: We recognize this counterparty and we are more than 90% confident that it is involved in this transaction.
    `MEDIUM`: We are moderately confident that this counterparty was involved in this transaction, but some details may differ from our records.
    `LOW`: We didn’t find a matching counterparty in our records, so we are returning a cleansed name parsed out of the request description.
    `UNKNOWN`: Error
    """
    entity_id: Optional[str] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('entity_id'), 'exclude': lambda f: f is Counterparty.UNSET }})
    r"""A unique, stable, Plaid-generated id that maps to the counterparty."""
    

