"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .creditamountwithcurrency import CreditAmountWithCurrency
from .creditbankincomehistoricalsummary import CreditBankIncomeHistoricalSummary
from dataclasses_json import Undefined, dataclass_json
from datetime import date
from plaid import utils
from typing import Any, Dict, List, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class CreditBankIncomeSummary:
    r"""Summary for bank income across all income sources and items (max history of 730 days)."""
    additional_properties: Optional[Dict[str, Any]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'exclude': lambda f: f is None }})
    end_date: Optional[date] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('end_date'), 'encoder': utils.dateisoformat(True), 'decoder': utils.datefromisoformat, 'exclude': lambda f: f is None }})
    r"""The latest date in which all income sources identified by Plaid appear in the user's account.
    The date will be returned in an ISO 8601 format (YYYY-MM-DD).
    """
    historical_summary: Optional[List[CreditBankIncomeHistoricalSummary]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('historical_summary'), 'exclude': lambda f: f is None }})
    income_categories_count: Optional[int] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('income_categories_count'), 'exclude': lambda f: f is None }})
    r"""Number of income categories per end user."""
    income_sources_count: Optional[int] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('income_sources_count'), 'exclude': lambda f: f is None }})
    r"""Number of income sources per end user."""
    income_transactions_count: Optional[int] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('income_transactions_count'), 'exclude': lambda f: f is None }})
    r"""Number of income transactions per end user."""
    iso_currency_code: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('iso_currency_code') }})
    r"""The ISO 4217 currency code of the amount or balance.
    Please use [`total_amounts`](https://plaid.com/docs/api/products/income/#credit-bank_income-get-response-bank-income-bank-income-summary-total-amounts) instead.

    Deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
    """
    start_date: Optional[date] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('start_date'), 'encoder': utils.dateisoformat(True), 'decoder': utils.datefromisoformat, 'exclude': lambda f: f is None }})
    r"""The earliest date within the days requested in which all income sources identified by Plaid appear in a user's account.
    The date will be returned in an ISO 8601 format (YYYY-MM-DD).
    """
    total_amount: Optional[float] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('total_amount'), 'exclude': lambda f: f is None }})
    r"""Total amount of earnings across all the income sources in the end user's Items for the days requested by the client.
    This may return an incorrect value if the summary includes income sources in multiple currencies.
    Please use [`total_amounts`](https://plaid.com/docs/api/products/income/#credit-bank_income-get-response-bank-income-bank-income-summary-total-amounts) instead.

    Deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
    """
    total_amounts: Optional[List[CreditAmountWithCurrency]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('total_amounts'), 'exclude': lambda f: f is None }})
    r"""Total amount of earnings across all the income sources in the end user's Items for the days requested by the client.
    This can contain multiple amounts, with each amount denominated in one unique currency.
    """
    unofficial_currency_code: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('unofficial_currency_code') }})
    r"""The unofficial currency code associated with the amount or balance. Always `null` if `iso_currency_code` is non-null.
    Unofficial currency codes are used for currencies that do not have official ISO currency codes, such as cryptocurrencies and the currencies of certain countries.
    Please use [`total_amounts`](https://plaid.com/docs/api/products/income/#credit-bank_income-get-response-bank-income-bank-income-summary-total-amounts) instead.

    Deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
    """
    

