"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class CreditBankEmploymentWarningType(str, Enum):
    r"""The warning type which will always be `BANK_EMPLOYMENT_WARNING`."""
    BANK_EMPLOYMENT_WARNING = 'BANK_EMPLOYMENT_WARNING'
