"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class CreditBankIncomeAccountType(str, Enum):
    r"""The account type. This will always be `depository`."""
    DEPOSITORY = 'depository'
