"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from plaid import utils
from typing import Any, Dict, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class CreditDocumentMetadata:
    r"""Object representing metadata pertaining to the document."""
    UNSET='__SPEAKEASY_UNSET__'
    document_type: Optional[str] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('document_type') }})
    r"""The type of document.

    `PAYSTUB`: A paystub.

    `BANK_STATEMENT`: A bank statement.

    `US_TAX_W2`: A W-2 wage and tax statement provided by a US employer reflecting wages earned by the employee.

    `US_MILITARY_ERAS`: An electronic Retirement Account Statement (eRAS) issued by the US military.

    `US_MILITARY_LES`: A Leave and Earnings Statement (LES) issued by the US military.

    `US_MILITARY_CLES`: A Civilian Leave and Earnings Statment (CLES) issued by the US military.

    `GIG`: Used to indicate that the income is related to gig work. Does not necessarily correspond to a specific document type.

    `PLAID_GENERATED_PAYSTUB_PDF`: Used to indicate that the PDF for the paystub was generated by Plaid.

    `NONE`: Used to indicate that there is no underlying document for the data.

    `UNKNOWN`: Document type could not be determined.
    """
    download_url: Optional[str] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('download_url') }})
    r"""Signed URL to retrieve the underlying file. This download URL can only be used once and expires after two minutes. To generate a new download URL, call `/credit/payroll_income/get` again."""
    name: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('name') }})
    r"""The name of the document."""
    status: Optional[str] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('status') }})
    r"""The processing status of the document.

    `PROCESSING_COMPLETE`: The document was successfully processed.

    `DOCUMENT_ERROR`: The document could not be processed. Possible causes include: The document was an unacceptable document type such as an offer letter or bank statement, the document image was cropped or blurry, or the document was corrupted.

    `UNKNOWN` or `null`: An internal error occurred. If this happens repeatedly, contact support or your Plaid account manager.
    """
    additional_properties: Optional[Dict[str, Any]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'exclude': lambda f: f is None }})
    page_count: Optional[int] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('page_count'), 'exclude': lambda f: f is CreditDocumentMetadata.UNSET }})
    r"""The number of pages of the uploaded document (if available)."""
    

