"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .creditdocumentmetadata import CreditDocumentMetadata
from .creditpaystubemployee import CreditPayStubEmployee
from .creditpaystubemployer import CreditPayStubEmployer
from .w2box12 import W2Box12
from .w2stateandlocalwages import W2StateAndLocalWages
from dataclasses_json import Undefined, dataclass_json
from plaid import utils
from typing import Any, Dict, List, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class CreditW2:
    r"""W2 is an object that represents income data taken from a W2 tax document."""
    UNSET='__SPEAKEASY_UNSET__'
    allocated_tips: Optional[str] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('allocated_tips') }})
    r"""Allocated tips."""
    box_12: List[W2Box12] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('box_12') }})
    box_9: Optional[str] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('box_9') }})
    r"""Contents from box 9 on the W2."""
    dependent_care_benefits: Optional[str] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('dependent_care_benefits') }})
    r"""Dependent care benefits."""
    document_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('document_id') }})
    r"""An identifier of the document referenced by the document metadata."""
    document_metadata: CreditDocumentMetadata = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('document_metadata') }})
    r"""Object representing metadata pertaining to the document."""
    employee: CreditPayStubEmployee = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('employee') }})
    r"""Data about the employee."""
    employer: CreditPayStubEmployer = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('employer') }})
    r"""Information about the employer on the pay stub."""
    employer_id_number: Optional[str] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('employer_id_number') }})
    r"""An employee identification number or EIN."""
    federal_income_tax_withheld: Optional[str] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('federal_income_tax_withheld') }})
    r"""Federal income tax withheld for the tax year."""
    medicare_tax_withheld: Optional[str] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('medicare_tax_withheld') }})
    r"""Medicare tax withheld for the tax year."""
    medicare_wages_and_tips: Optional[str] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('medicare_wages_and_tips') }})
    r"""Wages and tips from medicare."""
    nonqualified_plans: Optional[str] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('nonqualified_plans') }})
    r"""Nonqualified plans."""
    other: Optional[str] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('other') }})
    r"""Other."""
    retirement_plan: Optional[str] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('retirement_plan') }})
    r"""Retirement plan."""
    social_security_tax_withheld: Optional[str] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('social_security_tax_withheld') }})
    r"""Social security tax withheld for the tax year."""
    social_security_tips: Optional[str] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('social_security_tips') }})
    r"""Tips from social security."""
    social_security_wages: Optional[str] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('social_security_wages') }})
    r"""Wages from social security."""
    state_and_local_wages: List[W2StateAndLocalWages] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('state_and_local_wages') }})
    statutory_employee: Optional[str] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('statutory_employee') }})
    r"""Statutory employee."""
    tax_year: Optional[str] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('tax_year') }})
    r"""The tax year of the W2 document."""
    third_party_sick_pay: Optional[str] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('third_party_sick_pay') }})
    r"""Third party sick pay."""
    wages_tips_other_comp: Optional[str] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('wages_tips_other_comp') }})
    r"""Wages from tips and other compensation."""
    additional_properties: Optional[Dict[str, Any]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'exclude': lambda f: f is None }})
    

