"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class CreditPayStubPayBasisType(str, Enum):
    r"""The explicit pay basis on the paystub (if present)."""
    SALARY = 'SALARY'
    HOURLY = 'HOURLY'
    COMMISSION = 'COMMISSION'
