"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from plaid import utils
from typing import Any, Dict, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class CreditFreddieMacReportingInformationVOA24:
    r"""Information about an report identifier and a report name."""
    reporting_information_identifier: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('ReportingInformationIdentifier') }})
    r"""Documentation not found in the MISMO model viewer and not provided by Freddie Mac."""
    additional_properties: Optional[Dict[str, Any]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'exclude': lambda f: f is None }})
    report_date_time: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('ReportDateTime'), 'exclude': lambda f: f is None }})
    r"""Documentation not found in the MISMO model viewer and not provided by Freddie Mac."""
    report_identifier_type: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('ReportIdentifierType'), 'exclude': lambda f: f is None }})
    r"""Documentation not found in the MISMO model viewer and not provided by Freddie Mac. The value can only be \\"ReportID\\" """
    

