"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from plaid import utils
from typing import List, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class CreditPayrollIncomeRefreshRequestOptions:
    r"""An optional object for `/credit/payroll_income/refresh` request options."""
    item_ids: Optional[List[str]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('item_ids'), 'exclude': lambda f: f is None }})
    r"""An array of `item_id`s to be refreshed. Each `item_id` should uniquely identify a payroll income item."""
    webhook: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('webhook'), 'exclude': lambda f: f is None }})
    r"""The URL where Plaid will send the payroll income refresh webhook."""
    

