"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .assettype import AssetType
from dataclasses_json import Undefined, dataclass_json
from plaid import utils
from typing import Any, Dict, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class CreditFreddieMacAssetDetailVOE25:
    r"""Details about an asset."""
    asset_account_identifier: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('AssetAccountIdentifier') }})
    r"""A unique alphanumeric string identifying an asset."""
    asset_as_of_date: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('AssetAsOfDate') }})
    r"""Account Report As of Date / Create Date. Format YYYY-MM-DD"""
    asset_days_requested_count: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('AssetDaysRequestedCount') }})
    r"""The Number of days requested made to the Financial Institution. Example When looking for 3 months of data from the FI, pass in 90 days."""
    asset_description: Optional[str] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('AssetDescription') }})
    r"""A text description that further defines the Asset. This could be used to describe the shares associated with the stocks, bonds or mutual funds, retirement funds or business owned that the borrower has disclosed (named) as an asset."""
    asset_ownership_type: Optional[str] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('AssetOwnershipType') }})
    r"""Ownership type of the asset account."""
    asset_type: AssetType = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('AssetType') }})
    r"""A value from a MISMO prescribed list that specifies financial assets in a mortgage loan transaction. Assets may be either liquid or fixed and are associated with a corresponding asset amount."""
    asset_type_additional_description: Optional[str] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('AssetTypeAdditionalDescription') }})
    r"""Additional Asset Decription some examples are Investment Tax-Deferred , Loan, 401K, 403B, Checking, Money Market, Credit Card,ROTH,529,Biller,ROLLOVER,CD,Savings,Investment Taxable, IRA, Mortgage, Line Of Credit."""
    asset_unique_identifier: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('AssetUniqueIdentifier') }})
    r"""A vendor created unique Identifier."""
    additional_properties: Optional[Dict[str, Any]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'exclude': lambda f: f is None }})
    

