"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from plaid import utils
from typing import Any, Dict, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class DepositSwitchTokenCreateResponse:
    r"""DepositSwitchTokenCreateResponse defines the response schema for `/deposit_switch/token/create`"""
    UNSET='__SPEAKEASY_UNSET__'
    deposit_switch_token: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('deposit_switch_token') }})
    r"""Deposit switch token, used to initialize Link for the Deposit Switch product"""
    deposit_switch_token_expiration_time: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('deposit_switch_token_expiration_time') }})
    r"""Expiration time of the token, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format"""
    request_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('request_id') }})
    r"""A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive."""
    additional_properties: Optional[Dict[str, Any]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'exclude': lambda f: f is None }})
    

