"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class DocumentDateOfBirthMatchCode(str, Enum):
    r"""A match summary describing the cross comparison between the subject's date of birth, extracted from the document image, and the date of birth they separately provided to the identity verification attempt."""
    MATCH = 'match'
    PARTIAL_MATCH = 'partial_match'
    NO_MATCH = 'no_match'
