"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class DocumentStatus(str, Enum):
    r"""An outcome status for this specific document submission. Distinct from the overall `documentary_verification.status` that summarizes the verification outcome from one or more documents."""
    SUCCESS = 'success'
    FAILED = 'failed'
    MANUALLY_APPROVED = 'manually_approved'
