"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class EnrichTransactionDirection(str, Enum):
    r"""The direction of the transaction from the perspective of the account holder:

    `OUTFLOW` - Includes outgoing transfers, purchases, and fees. (Typically represented as a negative value on checking accounts and debit cards and a positive value on credit cards.)

    `INFLOW` - Includes incoming transfers, refunds, and income. (Typically represented as a positive value on checking accounts and debit cards and a negative value on credit cards.)
    """
    INFLOW = 'INFLOW'
    OUTFLOW = 'OUTFLOW'
