"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class ExpirationDate(str, Enum):
    r"""A description of whether the associated document was expired when the verification was performed.

    Note: In the case where an expiration date is not present on the document or failed to be extracted, this value will be `no_data`.
    """
    NOT_EXPIRED = 'not_expired'
    EXPIRED = 'expired'
    NO_DATA = 'no_data'
