"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class FDXNotificationCategory(str, Enum):
    r"""Category of Notification"""
    SECURITY = 'SECURITY'
    MAINTENANCE = 'MAINTENANCE'
    FRAUD = 'FRAUD'
    CONSENT = 'CONSENT'
    NEW_DATA = 'NEW_DATA'
