"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class Form1099Type(str, Enum):
    r"""Form 1099 Type"""
    FORM_1099_TYPE_UNKNOWN = 'FORM_1099_TYPE_UNKNOWN'
    FORM_1099_TYPE_MISC = 'FORM_1099_TYPE_MISC'
    FORM_1099_TYPE_K = 'FORM_1099_TYPE_K'
