"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from plaid import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class IncomeVerificationDocumentsDownloadRequest:
    r"""IncomeVerificationDocumentsDownloadRequest defines the request schema for `/income/verification/documents/download`."""
    UNSET='__SPEAKEASY_UNSET__'
    access_token: Optional[str] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('access_token'), 'exclude': lambda f: f is IncomeVerificationDocumentsDownloadRequest.UNSET }})
    r"""The access token associated with the Item data is being requested for."""
    client_id: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('client_id'), 'exclude': lambda f: f is None }})
    r"""Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body."""
    document_id: Optional[str] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('document_id'), 'exclude': lambda f: f is IncomeVerificationDocumentsDownloadRequest.UNSET }})
    r"""The document ID to download. If passed, a single document will be returned in the resulting zip file, rather than all document"""
    income_verification_id: Optional[str] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('income_verification_id'), 'exclude': lambda f: f is IncomeVerificationDocumentsDownloadRequest.UNSET }})
    r"""The ID of the verification.

    Deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
    """
    secret: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('secret'), 'exclude': lambda f: f is None }})
    r"""Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body."""
    

