"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from plaid import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class InstitutionsSearchPaymentInitiationOptions:
    r"""Additional options that will be used to filter institutions by various Payment Initiation configurations."""
    UNSET='__SPEAKEASY_UNSET__'
    consent_id: Optional[str] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('consent_id'), 'exclude': lambda f: f is InstitutionsSearchPaymentInitiationOptions.UNSET }})
    r"""A unique ID identifying the payment consent"""
    payment_id: Optional[str] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('payment_id'), 'exclude': lambda f: f is InstitutionsSearchPaymentInitiationOptions.UNSET }})
    r"""A unique ID identifying the payment"""
    

