"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from plaid import utils
from typing import List, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class LiabilitiesGetRequestOptions:
    r"""An optional object to filter `/liabilities/get` results. If provided, `options` cannot be null."""
    account_ids: Optional[List[str]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('account_ids'), 'exclude': lambda f: f is None }})
    r"""A list of accounts to retrieve for the Item.

    An error will be returned if a provided `account_id` is not associated with the Item
    """
    

