"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .linkdeliverycommunicationmethod import LinkDeliveryCommunicationMethod
from dataclasses_json import Undefined, dataclass_json
from plaid import utils
from typing import List, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class LinkDeliveryRecipient:
    r"""Metadata related to the recipient. If the information required to populate this field is not available, leave it blank."""
    communication_methods: Optional[List[LinkDeliveryCommunicationMethod]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('communication_methods'), 'exclude': lambda f: f is None }})
    r"""The list of communication methods to send the Hosted Link session URL to. If delivery is not required, leave this field blank."""
    first_name: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('first_name'), 'exclude': lambda f: f is None }})
    r"""First name of the recipient. Will be used in the body of the email / text (if configured). If this information is not available, leave this field blank."""
    

