"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class LoanIdentifierType(str, Enum):
    r"""A value from a MISMO prescribed list that specifies the type of loan identifier."""
    LENDER_LOAN = 'LenderLoan'
    UNIVERSAL_LOAN = 'UniversalLoan'
