"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class LoanAccountSubtype(str, Enum):
    r"""Valid account subtypes for loan accounts. For a list containing descriptions of each subtype, see [Account schemas](https://plaid.com/docs/api/accounts/#StandaloneAccountType-loan)."""
    AUTO = 'auto'
    BUSINESS = 'business'
    COMMERCIAL = 'commercial'
    CONSTRUCTION = 'construction'
    CONSUMER = 'consumer'
    HOME_EQUITY = 'home equity'
    LOAN = 'loan'
    MORTGAGE = 'mortgage'
    LINE_OF_CREDIT = 'line of credit'
    STUDENT = 'student'
    OTHER = 'other'
    ALL = 'all'
