"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class PaymentAmountCurrency(str, Enum):
    r"""The ISO-4217 currency code of the payment. For standing orders and payment consents, `\\"GBP\\"` must be used. For Poland, Denmark, Sweden and Norway, only the local currency is currently supported."""
    GBP = 'GBP'
    EUR = 'EUR'
    PLN = 'PLN'
    SEK = 'SEK'
    DKK = 'DKK'
    NOK = 'NOK'
