"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class PaymentInitiationConsentStatus(str, Enum):
    r"""The status of the payment consent.

    `UNAUTHORISED`: Consent created, but requires user authorisation.

    `REJECTED`: Consent authorisation was rejected by the user and/or the bank.

    `AUTHORISED`: Consent is active and ready to be used.

    `REVOKED`: Consent has been revoked and can no longer be used.

    `EXPIRED`: Consent is no longer valid.
    """
    UNAUTHORISED = 'UNAUTHORISED'
    AUTHORISED = 'AUTHORISED'
    REVOKED = 'REVOKED'
    REJECTED = 'REJECTED'
    EXPIRED = 'EXPIRED'
