"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .documentrisksignalsobject import DocumentRiskSignalsObject
from dataclasses_json import Undefined, dataclass_json
from plaid import utils
from typing import Any, Dict, List, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class PayrollRiskSignalsItem:
    r"""Object containing fraud risk data pertaining to the Item linked as part of the verification."""
    UNSET='__SPEAKEASY_UNSET__'
    item_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('item_id') }})
    r"""The `item_id` of the Item associated with this webhook, warning, or error"""
    verification_risk_signals: List[DocumentRiskSignalsObject] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('verification_risk_signals') }})
    r"""Array of payroll income document authenticity data retrieved for each of the user's accounts."""
    additional_properties: Optional[Dict[str, Any]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'exclude': lambda f: f is None }})
    

