"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from plaid import utils
from typing import Any, Dict, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class PayrollIncomeRateOfPay:
    r"""An object representing the rate at which an individual is paid."""
    UNSET='__SPEAKEASY_UNSET__'
    additional_properties: Optional[Dict[str, Any]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'exclude': lambda f: f is None }})
    pay_amount: Optional[float] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('pay_amount'), 'exclude': lambda f: f is PayrollIncomeRateOfPay.UNSET }})
    r"""The amount at which an employee is paid."""
    pay_rate: Optional[str] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('pay_rate'), 'exclude': lambda f: f is PayrollIncomeRateOfPay.UNSET }})
    r"""The rate at which an employee is paid."""
    

