"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .signaldevice import SignalDevice
from .signaluser import SignalUser
from dataclasses_json import Undefined, dataclass_json
from plaid import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class ProcessorSignalEvaluateRequest:
    r"""ProcessorSignalEvaluateRequest defines the request schema for `/processor/signal/evaluate`"""
    UNSET='__SPEAKEASY_UNSET__'
    amount: float = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('amount') }})
    r"""The transaction amount, in USD (e.g. `102.05`)"""
    client_transaction_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('client_transaction_id') }})
    r"""The unique ID that you would like to use to refer to this transaction. For your convenience mapping your internal data, you could use your internal ID/identifier for this transaction. The max length for this field is 36 characters."""
    processor_token: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('processor_token') }})
    r"""The processor token obtained from the Plaid integration partner. Processor tokens are in the format: `processor-<environment>-<identifier>`"""
    client_id: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('client_id'), 'exclude': lambda f: f is None }})
    r"""Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body."""
    client_user_id: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('client_user_id'), 'exclude': lambda f: f is None }})
    r"""A unique ID that identifies the end user in your system. This ID is used to correlate requests by a user with multiple Items. Personally identifiable information, such as an email address or phone number, should not be used in the `client_user_id`."""
    default_payment_method: Optional[str] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('default_payment_method'), 'exclude': lambda f: f is ProcessorSignalEvaluateRequest.UNSET }})
    r"""The default ACH or non-ACH payment method to complete the transaction.
    `SAME_DAY_ACH`: Same Day ACH by NACHA. The debit transaction is processed and settled on the same day
    `NEXT_DAY_ACH`: Next Day ACH settlement for debit transactions, offered by some payment processors
    `STANDARD_ACH`: standard ACH by NACHA
    `REAL_TIME_PAYMENTS`: real-time payments such as RTP and FedNow
    `DEBIT_CARD`: if the default payment is over debit card networks
    `MULTIPLE_PAYMENT_METHODS`: if there is no default debit rail or there are multiple payment methods
    Possible values:  `SAME_DAY_ACH`, `NEXT_DAY_ACH`, `STANDARD_ACH`, `REAL_TIME_PAYMENTS`, `DEBIT_CARD`, `MULTIPLE_PAYMENT_METHODS`
    """
    device: Optional[SignalDevice] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('device'), 'exclude': lambda f: f is None }})
    r"""Details about the end user's device"""
    is_recurring: Optional[bool] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('is_recurring'), 'exclude': lambda f: f is ProcessorSignalEvaluateRequest.UNSET }})
    r"""**true** if the ACH transaction is a recurring transaction; **false** otherwise"""
    secret: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('secret'), 'exclude': lambda f: f is None }})
    r"""Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body."""
    user: Optional[SignalUser] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('user'), 'exclude': lambda f: f is None }})
    r"""Details about the end user initiating the transaction (i.e., the account holder)."""
    user_present: Optional[bool] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('user_present'), 'exclude': lambda f: f is ProcessorSignalEvaluateRequest.UNSET }})
    r"""`true` if the end user is present while initiating the ACH transfer and the endpoint is being called; `false` otherwise (for example, when the ACH transfer is scheduled and the end user is not present, or you call this endpoint after the ACH transfer but before submitting the Nacha file for ACH processing)."""
    

