"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class RiskCheckEmailDomainIsCustom(str, Enum):
    r"""Indicates whether the email address domain is custom if known, i.e. a company domain and not free or disposable."""
    YES = 'yes'
    NO = 'no'
    NO_DATA = 'no_data'
