"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from plaid import utils
from typing import Any, Dict, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class RiskCheckSyntheticIdentity:
    r"""Field containing the data used in determining the outcome of the synthetic identity risk check.

    Contains the following fields:

    `score` - A score from 0 to 100 indicating the likelihood that the user is a synthetic identity.
    """
    UNSET='__SPEAKEASY_UNSET__'
    score: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('score') }})
    r"""A score from 0 to 100 indicating the likelihood that the user is a synthetic identity."""
    additional_properties: Optional[Dict[str, Any]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'exclude': lambda f: f is None }})
    

