"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .riskchecklinkedservice import RiskCheckLinkedService
from dataclasses_json import Undefined, dataclass_json
from plaid import utils
from typing import Any, Dict, List, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class RiskCheckPhone:
    r"""Result summary object specifying values for `phone` attributes of risk check."""
    linked_services: List[RiskCheckLinkedService] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('linked_services') }})
    r"""A list of online services where this phone number has been detected to have accounts or other activity."""
    additional_properties: Optional[Dict[str, Any]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'exclude': lambda f: f is None }})
    

