"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class SandboxBankIncomeWebhookFireRequestWebhookCode(str, Enum):
    r"""The webhook codes this endpoint can be used to test"""
    BANK_INCOME_REFRESH_UPDATE = 'BANK_INCOME_REFRESH_UPDATE'
    BANK_INCOME_REFRESH_COMPLETE = 'BANK_INCOME_REFRESH_COMPLETE'
