"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from plaid import utils
from typing import Any, Dict, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class SandboxItemFireWebhookResponse:
    r"""SandboxItemFireWebhookResponse defines the response schema for `/sandbox/item/fire_webhook`"""
    request_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('request_id') }})
    r"""A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive."""
    webhook_fired: bool = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('webhook_fired') }})
    r"""Value is `true`  if the test` webhook_code`  was successfully fired."""
    additional_properties: Optional[Dict[str, Any]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'exclude': lambda f: f is None }})
    

