"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .incomeverificationsourcetype import IncomeVerificationSourceType
from .sandboxpublictokencreaterequestincomeverificationbankincome import SandboxPublicTokenCreateRequestIncomeVerificationBankIncome
from dataclasses_json import Undefined, dataclass_json
from plaid import utils
from typing import List, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class SandboxPublicTokenCreateRequestOptionsIncomeVerification:
    r"""A set of parameters for income verification options. This field is required if `income_verification` is included in the `initial_products` array."""
    bank_income: Optional[SandboxPublicTokenCreateRequestIncomeVerificationBankIncome] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('bank_income'), 'exclude': lambda f: f is None }})
    r"""Specifies options for Bank Income. This field is required if `income_verification` is included in the `initial_products` array and `bank` is specified in `income_source_types`."""
    income_source_types: Optional[List[IncomeVerificationSourceType]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('income_source_types'), 'exclude': lambda f: f is None }})
    r"""The types of source income data that users will be permitted to share. Options include `bank` and `payroll`. Currently you can only specify one of these options."""
    

