"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class TaxpayerIdentifierType(str, Enum):
    r"""A value from a MISMO prescribed list that classifies identification numbers used by the Internal Revenue Service (IRS) in the administration of tax laws. A Social Security number (SSN) is issued by the SSA; all other taxpayer identification numbers are issued by the IRS."""
    INDIVIDUAL_TAXPAYER_IDENTIFICATION_NUMBER = 'IndividualTaxpayerIdentificationNumber'
    SOCIAL_SECURITY_NUMBER = 'SocialSecurityNumber'
