"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class TotalCanonicalDescription(str, Enum):
    r"""Commonly used term to describe the line item."""
    BONUS = 'BONUS'
    COMMISSION = 'COMMISSION'
    OVERTIME = 'OVERTIME'
    PAID_TIME_OFF = 'PAID TIME OFF'
    REGULAR_PAY = 'REGULAR PAY'
    VACATION = 'VACATION'
    EMPLOYEE_MEDICARE = 'EMPLOYEE MEDICARE'
    FICA = 'FICA'
    SOCIAL_SECURITY_EMPLOYEE_TAX = 'SOCIAL SECURITY EMPLOYEE TAX'
    MEDICAL = 'MEDICAL'
    VISION = 'VISION'
    DENTAL = 'DENTAL'
    NET_PAY = 'NET PAY'
    TAXES = 'TAXES'
    NOT_FOUND = 'NOT_FOUND'
    OTHER = 'OTHER'
    LESS_THAN_NIL_GREATER_THAN_ = '<nil>'
