"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class TransferDocumentPurpose(str, Enum):
    r"""Specifies the purpose of the uploaded file.

    `\"DUE_DILIGENCE\"` - The transfer due diligence document of the originator.
    The size of the document should be less than 20MB. Supported file extension: .pdf, .docx, .doc.
    """
    DUE_DILIGENCE = 'DUE_DILIGENCE'
