"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class TransactionsRuleField(str, Enum):
    r"""Transaction field for which the rule is defined."""
    TRANSACTION_ID = 'TRANSACTION_ID'
    NAME = 'NAME'
