"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class WalletPaymentScheme(str, Enum):
    r"""The payment scheme used to execute this transaction. This is present only for transaction types `PAYOUT` and `REFUND`.

    `FASTER_PAYMENTS`: The standard payment scheme within the UK.

    `SEPA_CREDIT_TRANSFER`: The standard payment to a beneficiary within the SEPA area.

    `SEPA_CREDIT_TRANSFER_INSTANT`: Instant payment to a beneficiary within the SEPA area.
    """
    FASTER_PAYMENTS = 'FASTER_PAYMENTS'
    SEPA_CREDIT_TRANSFER = 'SEPA_CREDIT_TRANSFER'
    SEPA_CREDIT_TRANSFER_INSTANT = 'SEPA_CREDIT_TRANSFER_INSTANT'
