"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class WebhookType(str, Enum):
    r"""The webhook types that can be fired by this test endpoint."""
    AUTH = 'AUTH'
    HOLDINGS = 'HOLDINGS'
    INVESTMENTS_TRANSACTIONS = 'INVESTMENTS_TRANSACTIONS'
    ITEM = 'ITEM'
    LIABILITIES = 'LIABILITIES'
    TRANSACTIONS = 'TRANSACTIONS'
    ASSETS = 'ASSETS'
