"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import processorstripebankaccounttokencreateresponse as components_processorstripebankaccounttokencreateresponse
from typing import Optional


@dataclasses.dataclass
class ProcessorStripeBankAccountTokenCreateResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    processor_stripe_bank_account_token_create_response: Optional[components_processorstripebankaccounttokencreateresponse.ProcessorStripeBankAccountTokenCreateResponse] = dataclasses.field(default=None)
    r"""OK"""
    

